/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wheelly_whater_NativeRippler */

#ifndef _Included_com_wheelly_whater_NativeRippler
#define _Included_com_wheelly_whater_NativeRippler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wheelly_whater_NativeRippler
 * Method:    transformRipples
 * Signature: (II[S[S[I[IZ)V
 */
JNIEXPORT void JNICALL Java_com_wheelly_whater_NativeRippler_transformRipples
  (JNIEnv *, jobject, jint, jint, jshortArray, jshortArray, jintArray, jintArray, jboolean);

/*
 * Class:     com_wheelly_whater_NativeRippler
 * Method:    disturb
 * Signature: (IIIIS[SZ)V
 */
JNIEXPORT void JNICALL Java_com_wheelly_whater_NativeRippler_disturb
  (JNIEnv *, jobject, jint, jint, jint, jint, jshort, jshortArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
